name: Build

on: [workflow_dispatch]

jobs:
  build_docker:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: lubo1994/mv-extractor:dev
          cache-from: type=registry,ref=lubo1994/mv-extractor:buildcache
          cache-to: type=registry,ref=lubo1994/mv-extractor:buildcache,mode=max

  build_wheels:
    name: Build wheels for cp${{ matrix.python }}-${{ matrix.platform_id }}
    runs-on: ${{ matrix.os }}
    needs: build_docker
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          python: 39
          bitness: 64
          platform_id: manylinux_x86_64
          manylinux_image: lubo1994/mv-extractor:dev
        - os: ubuntu-latest
          python: 310
          bitness: 64
          platform_id: manylinux_x86_64
          manylinux_image: lubo1994/mv-extractor:dev
        - os: ubuntu-latest
          python: 311
          bitness: 64
          platform_id: manylinux_x86_64
          manylinux_image: lubo1994/mv-extractor:dev
        - os: ubuntu-latest
          python: 312
          bitness: 64
          platform_id: manylinux_x86_64
          manylinux_image: lubo1994/mv-extractor:dev
        - os: ubuntu-latest
          python: 313
          bitness: 64
          platform_id: manylinux_x86_64
          manylinux_image: lubo1994/mv-extractor:dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          # Disable building PyPy wheels on all platforms
          CIBW_SKIP: pp*
          CIBW_ARCHS: x86_64
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          #CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_BUILD_FRONTEND: build
          CIBW_TEST_COMMAND: VIDEO_URL={project}/vid_h264.mp4 python3 {project}/tests/tests.py
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: python-wheel-${{ matrix.python }}
          path: ./wheelhouse/*.whl
